// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxaydlaunddpwccskaii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4YXlkbGF1bmRkcHdjY3NrYWlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNDYwNzUsImV4cCI6MjA2NzcyMjA3NX0.WEy1XXjhBnORIHiJuSW2pouygW-FKMid31-LQ4HJnXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});